-- Agent Bootstrap Widget
-- Hands control of configured players to AgentBridge AI in multiplayer games.
-- Config: LuaUI/Config/agent_bootstrap_config.lua (generated by game-manager)

function widget:GetInfo()
    return {
        name    = "Agent Bootstrap",
        desc    = "Hands control of configured players to AgentBridge AI",
        author  = "afcomech",
        version = "0.1",
        date    = "2026",
        license = "MIT",
        layer   = 0,
        enabled = true,
    }
end

local CONFIG_PATH = "LuaUI/Config/agent_bootstrap_config.lua"
local config = nil

function widget:Initialize()
    Spring.Echo("[AgentBootstrap] Initialize()")
    local ok, parsed = pcall(VFS.Include, CONFIG_PATH, nil, VFS.RAW_FIRST)
    if not ok then
        Spring.Echo("[AgentBootstrap] pcall failed: " .. tostring(parsed))
        widgetHandler:RemoveWidget(self)
        return
    end
    if not parsed or not parsed.players then
        Spring.Echo("[AgentBootstrap] No valid config at " .. CONFIG_PATH .. ", widget inactive")
        widgetHandler:RemoveWidget(self)
        return
    end

    config = parsed
    Spring.Echo("[AgentBootstrap] Config loaded OK")
end

local function doAiControl()
    if not config then
        Spring.Echo("[AgentBootstrap] No config")
        return false
    end

    local myPlayerID = Spring.GetMyPlayerID()
    local myName = Spring.GetPlayerInfo(myPlayerID)
    Spring.Echo("[AgentBootstrap] myPlayerID=" .. tostring(myPlayerID) .. " myName=" .. tostring(myName))

    local entry = config.players[myName]
    if entry then
        local ai = entry.ai or "AgentBridge"
        local version = entry.version or "0.1"
        -- GetPlayerInfo returns: name, active, spectator, teamID, ...
        local _, _, _, teamID = Spring.GetPlayerInfo(myPlayerID)
        local cmd = "aicontrol " .. tostring(teamID) .. " " .. ai .. " " .. version
        Spring.Echo("[AgentBootstrap] Sending: " .. cmd)
        Spring.SendCommands(cmd)
        return true
    else
        Spring.Echo("[AgentBootstrap] No entry for player '" .. tostring(myName) .. "'")
        return false
    end
end

local aiControlDone = false

-- Try early: GamePreload fires after loading but before game start,
-- giving the AI's init() time to set commander and start position.
function widget:GamePreload()
    Spring.Echo("[AgentBootstrap] GamePreload()")
    aiControlDone = doAiControl()
end

-- Fallback: if GamePreload didn't work, try again at GameStart.
function widget:GameStart()
    if not aiControlDone then
        Spring.Echo("[AgentBootstrap] GameStart() — fallback")
        doAiControl()
    end
end
